import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <main>
       <p>Este es mi index</p>
       <p><a href="/hola">Ir a hola mundo</a></p>
       <p><Link href="/hola">Ir a hola mundo con Link</Link></p>
     </main>
    </div>
  )
}
